name: Release Build

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build'
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - ios
        - android
      profile:
        description: 'Build profile'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - preview
      submit:
        description: 'Auto-submit to app stores'
        required: false
        default: false
        type: boolean

concurrency:
  group: release-build-${{ github.ref }}
  cancel-in-progress: false # Don't cancel in-progress builds

jobs:
  build:
    name: EAS Build
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      CI: true
      EXPO_NO_INTERACTIVE: 1
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "$EXPO_TOKEN" ]; then
            echo "::error::EXPO_TOKEN secret is not set. Please add it to your repository secrets."
            exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: EAS Build - All Platforms
        if: ${{ inputs.platform == 'all' }}
        run: |
          if [ "${{ inputs.submit }}" == "true" ]; then
            eas build --platform all --profile ${{ inputs.profile }} --auto-submit --non-interactive
          else
            eas build --platform all --profile ${{ inputs.profile }} --non-interactive
          fi

      - name: EAS Build - iOS
        if: ${{ inputs.platform == 'ios' }}
        run: |
          if [ "${{ inputs.submit }}" == "true" ]; then
            eas build --platform ios --profile ${{ inputs.profile }} --auto-submit --non-interactive
          else
            eas build --platform ios --profile ${{ inputs.profile }} --non-interactive
          fi

      - name: EAS Build - Android
        if: ${{ inputs.platform == 'android' }}
        run: |
          if [ "${{ inputs.submit }}" == "true" ]; then
            eas build --platform android --profile ${{ inputs.profile }} --auto-submit --non-interactive
          else
            eas build --platform android --profile ${{ inputs.profile }} --non-interactive
          fi

      - name: Comment on PR (if applicable)
        if: github.event_name == 'workflow_dispatch' && github.event.pull_request
        uses: actions/github-script@v7
        with:
          script: |
            const { platform, profile, submit } = context.payload.inputs;
            const submitText = submit === 'true' ? ' and submitted to app stores' : '';
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 Native build completed for **${platform}** using **${profile}** profile${submitText}!`
            });
